name: Lint, Build & Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read    
  pages: write       
  id-token: write  

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint JS
        run: npm run lint:js

      - name: Lint SCSS
        run: npm run lint:scss

      - name: Format code
        run: npm run format

      - name: Build site
        run: |
          mkdir -p dist/js
          cp index.html dist/
          cp -r js/* dist/js/
          npx sass styles/progress.scss dist/style.css

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
